repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.8.0
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 21.6b0
      hooks:
          - id: black
