name: Format

on: [push, pull_request]

jobs:
    Format:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9.4
            - uses: snok/install-poetry@v1.1.2
              with:
                  version: 1.1.6
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Before Install
              run: |
                  python --version
            - name: Install
              run: |
                  poetry install
            - name: Check Format
              run: |
                  poetry run task format-check
